---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemesh-full-node-a
  namespace: openshift-gitops
spec:
  destination:
    namespace: observability
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valuesObject:
        env:
          - name: JUMPS
            value: '2'
          - name: ID
            value: A
          - name: CHAIN_SVC
            value: 'http://servicemesh-full-node-b:3000/chain'
          - name: COLLECTOR_ENDPOINT
            value: 'http://tempo-sample-distributor.observability.svc.cluster.local:4318'
          - name: ENABLE_METRICS
            value: true
          - name: ENABLE_TRACING
            value: true
        fullnameOverride: servicemesh-full-node-a
        image:
          name: quay.io/casimon/servicemesh-full-node
          pullPolicy: Always
          tag: otel
          local: false
        extraAnnotations:
          app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"servicemesh-full-node-b"}]'
          prometheus.io/scrape: "true"
          prometheus.io/port: "3000"
          prometheus.io/scheme: "http"
        nameOverride: ''
        replicaCount: 1
        route:
          enable: true
          wildcardDomain: ""
        service:
          port: 3000
          type: ClusterIP
        servicemesh:
          gateway: servicemesh-node
          subset: v1
        extraLabels:
          - app.kubernetes.io/part-of: servicemesh-node
          - app.openshift.io/runtime: nodejs
    path: sm-component-chart
    repoURL: 'https://github.com/casimon-rh/servicemesh-full-demo'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
